Clean code
idanmalul/OBLI pull request #50
Opened 2021-10-30 12:36 UTC by manikant0018

Clean commented codes also un used functions. Proper commented related to functionality.

2021-10-31 07:47 UTC, razprod commented on application/controllers/BusinessThird.php
>          error_reporting(0);
I'd like to make a function that handle those line for different envs.
For example on DEV it should show errors but on production it must not.

2021-10-31 07:49 UTC, razprod commented on application/controllers/BusinessThird.php
> +        //The line is not in use but it will be usable when one server has two or more then two environments like production and dev
Not sure I understand what is done here
@manikant0018

2021-10-31 07:50 UTC, razprod commented on application/controllers/BusinessThird.php
> -    function business_third_Form4()
Does that function not in use?
@manikant0018

2021-10-31 07:53 UTC, razprod commented on application/controllers/BusinessThird.php
> +            //creating an url using user email
Do you mean 'path' ?
@manikant0018

2021-10-31 07:56 UTC, razprod commented on application/controllers/BusinessThird.php
> +    function business_without_payment_api()
Please leave a comment explaining this function usage
@manikant0018

2021-10-31 07:56 UTC, razprod commented on application/controllers/BusinessThird.php
> +    function businessThirdBadResponse()
Please explain this function usage
@manikant0018

2021-10-31 07:57 UTC, razprod commented on application/controllers/BusinessThird.php
>          $sql3 = "SELECT * FROM menu_section where status = 1";
Where's the usage of this $sql3 var?
@manikant0018

2021-10-31 07:58 UTC, razprod commented on application/controllers/BusinessThird.php
>          $data['logo_details'] = $this->project_model->get_query_result($sql6);
Why do we need to pull that data from DB? What is it used for?
@manikant0018

2021-10-31 07:58 UTC, manikant0018 commented on application/controllers/BusinessThird.php
>          error_reporting(0);
ok

2021-10-31 07:59 UTC, manikant0018 commented on application/controllers/BusinessThird.php
> +        //The line is not in use but it will be usable when one server has two or more then two environments like production and dev
There is a $_SERVER defined the comment is for that server variable

2021-10-31 08:00 UTC, razprod commented on application/controllers/BusinessThird.php
> -
Explain for me all this deletion.
@manikant0018

2021-10-31 08:00 UTC, razprod commented on application/controllers/BusinessThird.php
> -    }
Explain for me this deletion.
@manikant0018

2021-10-31 08:00 UTC, manikant0018 commented on application/controllers/BusinessThird.php
> -    function business_third_Form4()
Yes not in use

2021-10-31 08:01 UTC, razprod commented on application/controllers/BusinessThird.php
>          error_reporting(0);
@manikant0018 As you can see under 'issues' I've added new issue related to the above.
So only informing you )

2021-10-31 08:02 UTC, manikant0018 commented on application/controllers/BusinessThird.php
> +            //creating an url using user email
yes i think so. I dont have proper understanding about it. Its a very old functionality and previous developer build. But as I seen there us build an url

2021-10-31 08:03 UTC, manikant0018 commented on application/controllers/BusinessThird.php
> +    function business_without_payment_api()
ok

2021-10-31 08:03 UTC, razprod commented on application/controllers/BusinessThird.php
> +        //The line is not in use but it will be usable when one server has two or more then two environments like production and dev
$_SERVER["DOCUMENT_ROOT"] = $_SERVER["DOCUMENT_ROOT"];

Seems that you are taking that var value and assigning the same value to the same var. Why?

2021-10-31 08:04 UTC, manikant0018 commented on application/controllers/BusinessThird.php
> +    function businessThirdBadResponse()
ok

2021-10-31 08:04 UTC, manikant0018 commented on application/controllers/BusinessThird.php
>          $sql3 = "SELECT * FROM menu_section where status = 1";
I will check

2021-10-31 08:05 UTC, razprod commented on application/controllers/BusinessThird.php
> +    function business_without_payment_api()
You can do so by directly editing from here. If you navigate to that file from the commit you'll be able to edit that line )
You can also open that commit from github desktop and edit from vscode, what ever that works for you.

2021-10-31 08:05 UTC, manikant0018 commented on application/controllers/BusinessThird.php
>          $data['logo_details'] = $this->project_model->get_query_result($sql6);
Hopefully we are using banners or images there uploaded by Admin

2021-10-31 08:07 UTC, razprod commented on application/controllers/BusinessThird.php
>          $data['logo_details'] = $this->project_model->get_query_result($sql6);
Can you refer me to an example ?

2021-10-31 08:08 UTC, razprod commented on application/controllers/PrivateFlow.php
> -
Can you explain for me this deletion ?
@manikant0018

2021-10-31 08:08 UTC, razprod commented on application/controllers/PrivateFlow.php
> -    // private1 and private2 flow both
Explain this deletion as well.
@manikant0018

2021-10-31 08:10 UTC, razprod commented on application/controllers/PrivateFlow.php
> -    }
Explain this deletion as well.
@manikant0018

2021-10-31 08:10 UTC, razprod commented on application/controllers/PrivateFlow.php
> -
Is that function is now on api_helper?
@manikant0018

2021-10-31 08:11 UTC, razprod commented on application/controllers/PrivateFlow.php
> -
Explain this deletion.
@manikant0018

2021-10-31 08:12 UTC, razprod commented on application/controllers/PrivateFlow.php
> -    {
Explain this deletion.
@manikant0018

2021-10-31 08:12 UTC, razprod commented on application/controllers/PrivateFlow.php
> -    }
Explain this deletion.
@manikant0018

2021-10-31 08:13 UTC, razprod commented on application/controllers/Website.php
> -
Explain this deletion.
@manikant0018

2021-10-31 08:15 UTC, manikant0018 commented on application/controllers/BusinessThird.php
> -    }
I have updated above function on apis_helper. So that its not usable anymore here

2021-10-31 08:15 UTC, manikant0018 commented on application/controllers/PrivateFlow.php
> -
Not in use anymore

2021-10-31 08:16 UTC, razprod commented on application/controllers/Website.php
> -        $data['response'] = json_decode($request, true);
Explain this deletion.
@manikant0018

2021-10-31 08:17 UTC, manikant0018 commented on application/controllers/PrivateFlow.php
> -    // private1 and private2 flow both
The function is not in use

2021-10-31 08:18 UTC, manikant0018 commented on application/controllers/PrivateFlow.php
> -    }
Function is not in use

2021-10-31 08:18 UTC, manikant0018 commented on application/controllers/PrivateFlow.php
> -
yes

2021-10-31 08:19 UTC, manikant0018 commented on application/controllers/PrivateFlow.php
> -
We dont have any payment api method now. before long time ago we used Taraya payment API.

So not in use now

2021-10-31 08:20 UTC, manikant0018 commented on application/controllers/PrivateFlow.php
> -    {
These functions was build here for BDI and Paretix. Now we have common on helper. Not in use anymore

2021-10-31 08:21 UTC, manikant0018 commented on application/controllers/PrivateFlow.php
> -    }
We have no scan API. Function is used for demo purpose. not in use

2021-10-31 08:21 UTC, razprod requested changes
Please review this commit,
I want to understand each deletion.
Also application/controllers/Website.php has so many db queries which seem useless.
Please review them (also too many vars like $sql3-$sql6 -- confusing can be used by 1 var just re assign it's value.
@manikant0018

2021-10-31 08:21 UTC, manikant0018 commented on application/controllers/Website.php
> -
Not in use

2021-10-31 08:23 UTC, manikant0018 commented on application/controllers/Website.php
> -        $data['response'] = json_decode($request, true);
Not in use

2021-10-31 08:31 UTC, razprod reviewed
Please explain for me this approach.
How it works and why not not deleted from controllers if this approach should replace the manual load?

2021-10-31 08:39 UTC, razprod submitted a review, later dismissed
This commit looks good.
Clean and simple.
Not too much of changes as it should be.

2021-10-31 09:03 UTC, manikant0018 commented on application/controllers/BusinessThird.php
>          $data['logo_details'] = $this->project_model->get_query_result($sql6);
Seems expect to about us this sql is not needed anymore. I will remove with new merge soon.

2021-10-31 09:04 UTC, razprod commented on application/controllers/BusinessThird.php
>          $data['logo_details'] = $this->project_model->get_query_result($sql6);
Please commit to this branch not in a different one )

2021-10-31 09:10 UTC, manikant0018 commented on application/controllers/BusinessThird.php
> +        //The line is not in use but it will be usable when one server has two or more then two environments like production and dev
Suppose we have two environment ie

https://obli.co.il & https://obli.co.il/dev

for here dev environment whenever we use above server variable it belongs to production only. so simpally we can put it there like

$_SERVER["DOCUMENT_ROOT"] = $_SERVER["DOCUMENT_ROOT"].'/dev';

SO i am thinking line is useful when we needed.

2021-10-31 09:10 UTC, manikant0018 commented on application/controllers/BusinessThird.php
> +        //The line is not in use but it will be usable when one server has two or more then two environments like production and dev
If you wan I can remove the line?

2021-10-31 09:30 UTC, razprod commented on application/controllers/BusinessThird.php
> +        //The line is not in use but it will be usable when one server has two or more then two environments like production and dev
We should not be using our previous approach with envs.
This was only for the current mid transform between the envs.
Please delete because currently not in use.

2021-10-31 09:52 UTC, manikant0018 commented on application/controllers/BusinessThird.php
> +        //The line is not in use but it will be usable when one server has two or more then two environments like production and dev
With new merge removed

2021-10-31 09:55 UTC, razprod reviewed
This commit looks great.

2021-10-31 09:56 UTC, razprod commented on application/controllers/BusinessThird.php
> +        //The line is not in use but it will be usable when one server has two or more then two environments like production and dev
Can you refer me with a link to that commit?

2021-10-31 10:09 UTC, razprod commented on application/controllers/BusinessThird.php
> -    }
Explain this deletion.
@manikant0018

2021-10-31 10:12 UTC, razprod commented on application/controllers/BusinessThird.php
> +            //creating an url using user email
So we need to address that code to understand what it is used for.
Opening an issue related to this

2021-10-31 10:16 UTC, manikant0018 commented on application/controllers/BusinessThird.php
> -    }
I checked and found its not in use anymore

2021-10-31 10:16 UTC, razprod commented on application/controllers/BusinessThird.php
>          $data['logo_details'] = $this->project_model->get_query_result($sql6);
-- A commit has been made: 0f5fe2d859c5d7fd0a45b5f9e0e8fe840d1654f2

2021-10-31 10:18 UTC, manikant0018 commented on application/controllers/BusinessThird.php
> +        //The line is not in use but it will be usable when one server has two or more then two environments like production and dev
I think on same branch I did

2021-10-31 10:19 UTC, razprod commented on application/helpers/common_helper.php
>      $content = json_encode(array('htmlCode' => $html, 'pageSize' => 'a4'));
Please move the api key to config file.
Use same branch just add another commit.

2021-10-31 10:21 UTC, manikant0018 commented on application/controllers/BusinessThird.php
> +        //The line is not in use but it will be usable when one server has two or more then two environments like production and dev
![image](https://user-images.githubusercontent.com/67783147/139578075-1e332f06-b928-4cec-8f8c-4382e7e70c66.png)

2021-10-31 10:21 UTC, manikant0018 commented on application/helpers/common_helper.php
>      $content = json_encode(array('htmlCode' => $html, 'pageSize' => 'a4'));
ok sure

2021-10-31 10:23 UTC, razprod commented on application/controllers/BusinessThird.php
> +        //The line is not in use but it will be usable when one server has two or more then two environments like production and dev
Did for all controller which were added that line?

2021-10-31 10:31 UTC, manikant0018 commented on application/helpers/common_helper.php
>      $content = json_encode(array('htmlCode' => $html, 'pageSize' => 'a4'));
done @razprod

2021-10-31 10:33 UTC, razprod reviewed
Great commit with great changes.

2021-10-31 10:34 UTC, manikant0018 commented on application/controllers/BusinessThird.php
> +        //The line is not in use but it will be usable when one server has two or more then two environments like production and dev
yes

2021-10-31 10:48 UTC, manikant0018 commented on application/controllers/BusinessThird.php
>          $sql3 = "SELECT * FROM menu_section where status = 1";
We have removed from all controllers

2021-10-31 10:53 UTC, razprod commented on application/controllers/BusinessThird.php
>          $sql3 = "SELECT * FROM menu_section where status = 1";
Indeed, I see now.

2021-11-01 09:24 UTC, razprod commented on application/controllers/BusinessThird.php
> -
@manikant0018

2021-11-04 14:30 UTC, razprod commented
@manikant0018 Need to fix the conflicts here

2021-11-08 05:57 UTC, manikant0018 commented
> @manikant0018 Need to fix the conflicts here

Resolved

2021-11-08 07:28 UTC, razprod commented
> > @manikant0018 Need to fix the conflicts here
> 
> Resolved

Your PR was into 'master' I changed into 'Development'.
Please review the new conflicts.

2021-11-09 10:55 UTC, razprod commented
Closing this commit due the reason it has a merge from 'master' branch.
Fixing this problem and will reopen a new PR.

2021-11-09 10:55 UTC, closed without merging