Segnature upload path fixed
idanmalul/OBLI pull request #51
Opened 2021-10-30 14:57 UTC by manikant0018

Signature and profile picture upload path created

2021-10-31 09:47 UTC, razprod commented on application/controllers/BusinessThird.php
> +              $this->session->set_userdata('segnature_path',$this->config->item('segnature_path').'segnatures/'.$data['unique_id'].'/');
Please use a var that holds the signature path: `$this->config->item('segnature_path').'segnatures/'.$data['unique_id'].'/'`
Instead of re-writing multiple times.
Shorten workflow & prevent mistyping.
@manikant0018

2021-10-31 09:49 UTC, razprod commented on application/controllers/BusinessThird.php
> +               $this->session->set_userdata('profile_pic_path',$this->config->item('segnature_path').'profilepics/'.$data['unique_id'].'/');
Also here, use var that holds that path.

2021-10-31 09:51 UTC, razprod reviewed
It seems as if you're using general folders for all clients instead a specific folder for each client.
Or am I wrong, please refer me if I am.

2021-10-31 10:55 UTC, manikant0018 commented
Actually Raz, $this->config->item('segnature_path contains path of directory `upload`'

And accroding to upload file if its segnature we have directory name is segnature. .$data['unique_id'] provide client ID from flow.

SO we are creating client id folder within segnature or profilepic directory first and then we are upload the files here

2021-10-31 10:56 UTC, manikant0018 commented on application/controllers/BusinessThird.php
> +               $this->session->set_userdata('profile_pic_path',$this->config->item('segnature_path').'profilepics/'.$data['unique_id'].'/');
Already vars are there. you mean for `profilepics/`?

2021-10-31 10:58 UTC, razprod commented
> Actually Raz, $this->config->item('segnature_path contains path of directory `upload`'
> 
> And accroding to upload file if its segnature we have directory name is segnature. .$data['unique_id'] provide client ID from flow.
> 
> SO we are creating client id folder within segnature or profilepic directory first and then we are upload the files here

But what about the order's folder? It doesnt seem that there's folder for that order..

2021-10-31 10:59 UTC, razprod commented on application/controllers/BusinessThird.php
> +               $this->session->set_userdata('profile_pic_path',$this->config->item('segnature_path').'profilepics/'.$data['unique_id'].'/');
I mean like put in a var the whole value of `$this->config->item('segnature_path').'profilepics/'.$data['unique_id']`
then use that var instead the whole line itself.

2021-10-31 11:56 UTC, manikant0018 commented
@razprod changes made with the same branch. Please review once again and let me know if you want to something change. Thanks

2021-10-31 12:35 UTC, razprod commented on application/config/config.php
> +$config['segnature_path'] = 'clients/orders/';
Why is there 'orders' folder inside 'clients' folder?
Inside 'clients' folder should only be folder for each client.
Inside each client's folder, should be all the order of the client as folders.
Also inside the client's folder should be global folders for global files (profile pics etc - those who upload before order is created).
So:
Clients->some_client_folder_with_unique_id->(few global folders for global files) || (also folder for each order client has requested)

2021-10-31 12:36 UTC, razprod requested changes
https://github.com/idanmalul/OBLI/pull/51/files/bd0ee30a5efe07af8476bcdf07942a1749081147..eeebb1e87aaf9c1668064dd13b9315eaf320cb40#r739804551

Need you to address this comment.

2021-10-31 12:45 UTC, manikant0018 commented on application/config/config.php
> +$config['segnature_path'] = 'clients/orders/';
orders contains orders files. Already within orders folder we are creating folder according to clients order id

2021-10-31 13:10 UTC, razprod commented on application/config/config.php
> +$config['segnature_path'] = 'clients/orders/';
I want the logic to be 1 Main folder that holds everything related to uploads.
The main idea is 1 folder with subfolders of each client.
For each client folder, there will be subfolder for global files && subfolder for orders.
In orders folder there will be subfolders for each order.
For each order folder, there will be held all the related docs for that order.
ref:
![image](https://user-images.githubusercontent.com/87066774/139585101-b27b65ae-1a6d-497b-9da4-e13217ac869e.png)

2021-10-31 14:03 UTC, manikant0018 commented on application/config/config.php
> +$config['segnature_path'] = 'clients/orders/';
Its done according to above shared Flow chart @razprod

2021-10-31 14:10 UTC, razprod requested changes
It seems that only this file application/controllers/BusinessThird.php
has no handle for orders folder.
Let me know if I've missed that part please.

2021-10-31 14:10 UTC, razprod commented on application/config/config.php
> +$config['segnature_path'] = 'clients/orders/';
I've answered here:
https://github.com/idanmalul/OBLI/pull/51#pullrequestreview-793702807

2021-11-01 05:32 UTC, manikant0018 commented
No with all controllers same changes made. Also there is orders path defined within config file

https://github.com/idanmalul/OBLI/commit/68794ca51bb3a6a0d280dacae21532aefba2ab74

2021-11-01 09:19 UTC, razprod commented
> No with all controllers same changes made. Also there is orders path defined within config file
> 
> [68794ca](https://github.com/idanmalul/OBLI/commit/68794ca51bb3a6a0d280dacae21532aefba2ab74)

https://github.com/idanmalul/OBLI/blob/68794ca51bb3a6a0d280dacae21532aefba2ab74/application/controllers/BusinessThird.php#L153

https://github.com/idanmalul/OBLI/blob/68794ca51bb3a6a0d280dacae21532aefba2ab74/application/controllers/PrivateFlow.php#L279

As you can see, the second one uses 'orders' folder but the first one doesn't.

2021-11-01 09:46 UTC, manikant0018 commented
Oh I apologize @razprod , I fix and re merge it soon.

2021-11-01 09:58 UTC, razprod commented
> Oh I apologize @razprod , I fix and re merge it soon.

Sure, keep me posted

2021-11-01 10:16 UTC, manikant0018 commented
Fixed issues with code and re merged

2021-11-01 10:16 UTC, manikant0018 commented
> > Oh I apologize @razprod , I fix and re merge it soon.
> 
> Sure, keep me posted

done

2021-11-01 12:23 UTC, razprod reviewed
This commit looks great.

2021-11-01 12:25 UTC, razprod approved these changes

2021-11-01 12:26 UTC, razprod commented
@manikant0018 Have you tested this?

2021-11-02 12:10 UTC, manikant0018 commented
> @manikant0018 Have you tested this?

Yes tested but must be tested with Apple system also. The difference between windows and Apple related to permission.

2021-11-02 12:26 UTC, manikant0018 commented
> > @manikant0018 Have you tested this?
> 
> Yes tested but must be tested with Apple system also. The difference between windows and Apple related to permission.

#Functioanlity working but a small change required here. I will push again

2021-11-02 13:43 UTC, merged